[solution]
name = "sol-v1"      # Solution name
definition = "gated_delta_net"          # Track: fused_moe | sparse_attention | gated_delta_net
author = "kachua"              # Team/author name

[build]
language = "cuda"               # triton | cuda
entry_point = "gdn_v1"            # Kernel function name
