[solution]
name = "sol-v1"      # Solution name
definition = "gdn_decode_qk4_v8_d128_k_last"          # Concrete definition key from trace set
author = "kachua"              # Team/author name

[build]
language = "cuda"               # triton | cuda
binding = "torch"               # tvm-ffi | torch (for CUDA/CPP)
entry_point = "kernel.cu::launch_gdn_v1"  # Entry point: <file_path>::<function_name>
