[solution]
name = "gdn-decode-triton-v1"      # Solution name
definition = "gdn_decode_qk4_v8_d128_k_last"          # Concrete definition key from trace set
author = "kachua"              # Team/author name

[build]
language = "triton"               # triton | cuda
entry_point = "kernel.py::launch_gdn_v1"  # Entry point: <file_path>::<function_name>
